### ISSUE TITLE
Kerbals appears to have wrong size in some capsules

### ISSUE THREAD

**Issue by hendrixone** [KSP-RO/ROKerbalism#102]
I tried to run a clean install of ksp only with RO and the default recommended mod(without kerbalism RO config), and the kerbal in the pod seems fine. But when kerbalism is installed. kerbals in the MK1-3 are clearly oversized (Also happens to the Orion command pod in RO capsule mod. Other capsule such as Apollo cm are just fine.
I attached log and ckan down here if needed. I tried to solve this problem by my self but I am just not very familiar with how kerbalism works
[Kerbal Space Program.zip](https://github.com/KSP-RO/ROKerbalism/files/6767319/Kerbal.Space.Program.zip)

**Comment by hendrixone** [comment]
strangely enough, letting the kerbals go eva and re-board the vessel seems to be solving this bug. I guess that'll do for now

**Comment by SpaceODY** [comment]
I have the same issue. While doing an EVA fixes it I still and a bit annoyed i have to do it.
