### ISSUE TITLE
DECQ Buran config has some errors

### ISSUE THREAD

**Issue by drhead** [KSP-RO/ROKerbalism#130]
There's a few inaccuracies in the DECQ Buran config added in #124 that kind of break the vessel.  I am using this book as a source:
http://ftp.demec.ufpr.br/foguete/bibliografia/Energiya%20BURAN%20The%20Soviet%20Space%20Shuttle.pdf

Firstly, the scrubber should be a potassium superoxide scrubber (pg. 120).  The book says 6-18 cartridges for the scrubber.  I cannot find a proper citation for how much that actually is (I did find a figure somewhere else saying that a cartridge is 6L, but this wasn't specifically for Buran), but I suggest an estimate based on roughly 65 person-days of life support (that's a crew of 10 for roughly the nominal 7 day mission duration, or a crew of 2 for the maximum 30 day duration).  However, a lower estimate may be appropriate on the basis that extra life support materials should be installed in the cargo bay (pg.146).

Secondly, the aft compartment should have crossfeed enabled, since the Buran explicitly has crossfeed between the forward and aft RCS/OMS (pg.130).  This may result in taking some LOX intended for fuel cells, but this appears to be realistic and intended behavior that many proposed mission setups were explicitly designed around (pg.126).  The fuel tank has also been erroneously removed entirely, leaving no room for propellant.  The fuel tank should have room allowing a total of 7.5t of propellant mix across the entire orbiter (pg. 131), with optional fuel tanks to be installed in the cargo bay in a way that doesn't disturb the center of mass to get to a total of 14t.  It seems to be implied in the description on pg. 130 of the crew compartment sintin/LOX tanks, combined with the addon fuel tanks, that the propellant stores should be evenly split between the forward and aft compartments to respect the center of gravity.

Thirdly, the fuel cells are cited as having a total of 40kW continuous capacity between the four units (pg.123).  They produce "more than 100kg per day" of water as a byproduct, in case that is helpful for calculating power consumption.  I don't think I can find the diagram easily, but I know I found a diagram indicating the fuel cells are installed in the cargo bay along with the LH2/LOX tanks.  There is a 10L container for drinking water in the crew compartment, and a 400L tank of process water used for cooling and hydraulics that is filled and expected to be expended during liftoff (pg. 122), but I don't know the extent to which this is actually simulated.  Pg.146 cites long duration missions requiring an additional cryo kit, so the fuel cells should have enough for 8-10 days of power on their own.

**Comment by Capkirk123** [comment]
Should be resolved by https://github.com/KSP-RO/ROKerbalism/commit/fc6dd81e2fc22cb0a04e6de993c71a574389353e?
