### ISSUE TITLE
Lost all procedural experiments

### ISSUE THREAD

**Issue by billgarlic** [KSP-RO/ROKerbalism#131]
Upgraded to 1.2.7 via CKAN and all of the experiments configured for my procedural avionics disappeared.  It only happened once a craft became active.
Running RO and RP-1 latest installs via CKAN.
Reverted to 1.2.5 (I had never used 1.2.6 so I went back further) and it was fine, however, any craft I used during the time I was using 1.2.7 still had the experiments gone.

**Comment by NathanKell** [comment]
You don't have the latest RP-1 then.

Sent by my thumbs, slowly.

**Comment by billgarlic** [comment]
Sorry, CKAN was not identifying a new RP-1 version but I see now there was one on 8/15.  I am upgrading both and expect it will work.
