### ISSUE TITLE
Logspam in VAB: ResourceSimulator.Process_apiModule

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/ROKerbalism#134]
```
[LOG 15:13:19.858] [Kerbalism] ResourceSimulator.Process_apiModule resource count before call 0
[LOG 15:13:19.858] [Kerbalism] ResourceSimulator.Process_apiModule resource count after call 1
```

**Comment by Gordon-Dry** [comment]
If this is intended debug logging, then why is this enabled on a release version by default?
Every mod that uses limitless debug logging slows KSP by some intent and there are already some of those.

At least make it toggleable for experiended users, like inside the
`GameData\KerbalismConfig\Settings.cfg`

**Comment by siimav** [comment]
ROKerbalism is just configs and doesn't contain any "debug messages" or even DLLs.

**Comment by Gordon-Dry** [comment]
Okay then, but this kind of spamming does not occur in stock Kerbalism config.
So it's triggered by the ROKerbalism environment.
