### ISSUE TITLE
Switching vessels turns off fuel cells in all vessels

### ISSUE THREAD

**Issue by raymoo** [KSP-RO/ROKerbalism#135]
When switching to a vessel, that vessel and any other vessel with a fuel cell stops producing energy from the cell. This is distinct from the bug with dumping water and also doesn't happen in stock+Kerbalism. I have more details in the issue I posted for Kerbalism https://github.com/Kerbalism/Kerbalism/issues/834

There was an old issue on the RP-0 repository (https://github.com/KSP-RO/RP-0/issues/1548) that was closed as being a Kerbalism issue, but since I couldn't reproduce it without RO, I was hoping that maybe it could be fixed or worked around on the RO Kerbalism configs side.

**Comment by siimav** [comment]
Should be fixed by https://github.com/Kerbalism/Kerbalism/commit/d6400a0c3cf8d3db028bdf45f6dfb19f7bf6d3e8
