### ISSUE TITLE
Kerbalism Fuel Cells still consume stock generic oxidizer and not liquid oxygen

### ISSUE THREAD

**Issue by smunstu** [KSP-RO/ROKerbalism#143]
As the title says, I am experiencing a bug wherein my fuel cells consume a combination of liquid hydrogen and generic oxidizer, even though they are ostensibly configured to use the Gemini-era fuel cell process (hydrogen/oxygen reaction)

This makes building craft difficult, as the only fuel tanks that can hold generic oxidizer are the generic "service" tanks, (not the SM-I, SM-II, SM-III style tanks) which may or may not be another bug.

Problem is confirmed to exist with the 750kw Fuel Cell. I have not tried the internal fuel cells (like in Gemini/apollo service modules), or the larger fuel cells yet.

ModuleManager.ConfigCache
https://drive.google.com/file/d/1-3l8sOMwcq50DBsMCBpzyHYz7YyTgqkj/view?usp=sharing

**Comment by NathanKell** [comment]
Can't repro. You have a ModuleResourceConverter on that fuel cell, which means you must have either an outdated mod from us, or some mod that's not part of the Express Install that's adding it to the `FuelCell` part.

**Comment by Capkirk123** [comment]
Resolved in https://github.com/KSP-RO/ROKerbalism/commit/cb7578f0973b41aeabd0847b15241e0a5d65fa1c. CryoEngines adds its own fuel cell modules to the stock fuel cell, which were not being properly removed by kerbalism.
