### ISSUE TITLE
LCH4 to CH4 conversion

### ISSUE THREAD

**Issue by Mariner1981** [KSP-RO/ROKerbalism#152]
The possibility to use Methane and Oxygen for RCS-fuel was added to RO some time ago, however there is no way to bring gasious CH4 in a meaningfull way, without putting ginormous tanks on the vessel.

I suggest a LCH4 to CH4 and the vice versa process to be added to the liquifiër array. Perhaps also bigger LO2 to O2 and LH2 to H2 convertors to prevent having to paste a vessel with a dozen arrays to barely fill enough gas to keep up with a small RCS system.

As a metric perhaps require/use 1KW of power per process, considering active heating.

**Comment by Capkirk123** [comment]
Resolved by https://github.com/KSP-RO/ROKerbalism/commit/0040ad3c3c480e58ba27de47bc3a55b17d6a82d7
